### ISSUE TITLE
Typo on site page - 'ligher' should be 'lighter'.

### ISSUE THREAD

**Issue by dalhundal** [riccardoscalco/textures#1]
Under LINES, textures.lines.lighter() is misspelt.

![screenshot-riccardoscalco github io 2015-03-18 11-58-09](https://cloud.githubusercontent.com/assets/560101/6708198/209b1434-cd66-11e4-995f-828188763899.png)

**Comment by riccardoscalco** [comment]
Fixed, thanks.
