### ISSUE TITLE
Website exampels broken as //d3js.org/d3.v3.min.js is timing out on https

### ISSUE THREAD

**Issue by ichpuchtli** [riccardoscalco/textures#11]
d3js.org does not support https you must http explicitly. 

```html
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
````

**Comment by riccardoscalco** [comment]
Thanks for the tip. At the moment I hosted locally d3 and topojson, but I am going to implement a solution like this one: http://stackoverflow.com/questions/1014203/best-way-to-use-googles-hosted-jquery-but-fall-back-to-my-hosted-library-on-go

**Comment by ichpuchtli** [comment]
Could also use https://cdnjs.com/libraries/d3/ which supports both http and https

**Comment by riccardoscalco** [comment]
Thanks for the tip.
