### ISSUE TITLE
using with browserify

### ISSUE THREAD

**Issue by fionnbharra** [riccardoscalco/textures#12]
I've installed textures using `npm install textures --save-dev` but when I try and `require('textures');` it is returning as undefined.

**Comment by fewspider** [comment]
You can try this:)

##main.js

```
var xx = require('./node_modules/textures/textures.js')
console.log(xx)
```

build bundle.js
```
browserify main.js > bundle.js
```

test.html

```
<html>
  <head>
  <script src="bundle.js"></script>
  </head>
  <body>
  </body>
</html>
```

It is working.
![2015-03-22 19 27 32](https://cloud.githubusercontent.com/assets/3256161/6769123/92814f58-d0c9-11e4-9df1-0a149badb87a.png)

**Comment by fionnbharra** [comment]
Thanks, it's now working. I'm including like this - 

`var textures = require('textures/textures');`

Is this a problem with browserify? Is it possible to change it so you can simply use `require('textures');`

**Comment by fewspider** [comment]
You can closed this issue now

**Comment by fionnbharra** [comment]
Done.
