### ISSUE TITLE
Undefined on svg.call

### ISSUE THREAD

**Issue by amankapur** [riccardoscalco/textures#14]
d3 version 2.9.7

Usage: 

````
var t = textures.lines().thicker();
svg.call(t);
svg.style('fill', t.url());
````

`svg.call(t)` returns undefined inside d3's append child method.

**Comment by riccardoscalco** [comment]
Thanks, I will look into this issue in the next future. Btw, any particular reason for not using the updated version of d3?

**Comment by amankapur** [comment]
mostly too much legacy code. you think it's due to older d3 version ?

**Comment by riccardoscalco** [comment]
I would say no, but this pen seems doing what you want: http://codepen.io/riccardoscalco/pen/jEdbmE?editors=101

**Comment by amankapur** [comment]
i think it is: http://codepen.io/anon/pen/vEbNwM, i simply changed the d3 version to mine and it fails at the same place.

**Comment by riccardoscalco** [comment]
The older version seems not supporting multiple attribute definitions  within the same `attr` method.
Have a look at this:  http://codepen.io/riccardoscalco/pen/EaryGo?editors=101

**Comment by amankapur** [comment]
thanks.
