### ISSUE TITLE
Replace header .png with an .svg map of Italy

### ISSUE THREAD

**Issue by edouerd** [riccardoscalco/textures#21]
Hi there! :wave: 

I was just browsing for data visualization-related libraries and modules for the product I'm working on, and came across your amazing work [here](http://riccardoscalco.github.io/textures/).

While I was scrolling through the page, one of my devs walked by and stopped to check out what I was looking at. Impressed, he asked me if the map was also an .svg, and when I checked it out, we both discovered it wasn't.

I did a quick google and found [this awesome collection](http://www.amcharts.com/svg-maps/?map=italy) of country maps in svg format.

If you're feeling like updating the site anytime soon, maybe consider this resource so the whole page is rendered w/ svgs! :smile:

**Comment by riccardoscalco** [comment]
Hi édouard,

initially I used the svg version (created with d3 and then extracted with SVG Crowbar), here it is:
https://github.com/riccardoscalco/textures/blob/gh-pages/map.svg

Then Chrome introduced a bug on the rendering of certain svg patterns of a svg file, I waited a bit and then I decided to switch to the png version. Here you see the bug:
![bug](https://cloud.githubusercontent.com/assets/1370300/9954244/af643b84-5de7-11e5-8ab5-21d74a75287a.png)

By the way, the same bug does not affect the rendering of svg nodes created through js (d3 + textures), so there is still the possibility to have the svg version of the map.

Thanks for the link to the collection, it's very useful!
