### ISSUE TITLE
working with svg crowbar to export?

### ISSUE THREAD

**Issue by Fil** [riccardoscalco/textures#22]
Hello,

I would like to be able to export the textures to a svg file with a tool such as [svg crowbar](http://nytimes.github.io/svg-crowbar/); unfortunately it only seems to work in Inkscape — Illustrator or Affinity Designer don't find the textures. If I use Inkscape to export to PDF, then open the PDF in Illustrator, the textures are there but contain a small “border„ around each square, which is pretty ugly.

Do you have any idea of what can be missing? I can post example files.

**Comment by Fil** [comment]
I've investigated further in the SVG file produced and there are three things to modify on the exported files to make them work:

1. In the svg file, the patterns' `defs`  must appear before the painted paths

2. The URLs should not be exported as `http://…#xxx` but directly as `#xxx` (this might be an issue with crowbar)

3. d3 under all the browsers I've tried inserts `style='url("#xxx") none'` instead of  `style='url("#xxx")`. Replacing `none` with `transparent` does not work, only putting back to a pure `url()` call will do. (This might be an issue with d3 or with Firefox.)

With all this, the produced files are OK.

**Comment by riccardoscalco** [comment]
Thanks for the thread, it is instructive.

**Comment by petulla** [comment]
@Fil Have you created a crowbar that produces file outputs as you describe? I found the same.

**Comment by riccardoscalco** [comment]
Hi, recently I crossed this one https://github.com/Hypercubed/svgsaver, maybe it helps.

**Comment by petulla** [comment]
I'm using that. I've actually modified it so it does all of the routines needed above. Still having an issue where the def patterns don't repeat in browser but are fine in Illustrator.
