### ISSUE TITLE
TypeError: this.append is not a function

### ISSUE THREAD

**Issue by kgxsz** [riccardoscalco/textures#27]
Hi,

I'm hitting this error when implementing the "getting started" example on your webpage:

`textures.inc.js:208 Uncaught TypeError: this.append is not a function`

I'm using:
- `d3 v4.2.0`
- `textures v1.0.3`

Any ideas?

Cheers.

**Comment by riccardoscalco** [comment]
Hi, `textures v1.0.4` is compatible with `d3 v4.x`.
Here you can find a working example http://codepen.io/riccardoscalco/pen/BLyVGx.
