### ISSUE TITLE
Publish to https://cdnjs.com/

### ISSUE THREAD

**Issue by mcandre** [riccardoscalco/textures#34]
Please host static assets on a content delivery network such as CDNJS.com, so that developers can integrate Textures.js more easily into our applications!

**Comment by riccardoscalco** [comment]
Hi, thanks for the suggestion. I just added a comment in the readme. Please have a look at https://github.com/riccardoscalco/textures/commit/c1a3e80f1b605ccacee8999949559f5d4275bea1.
