### ISSUE TITLE
Example chart integrations

### ISSUE THREAD

**Issue by mcandre** [riccardoscalco/textures#35]
Please provide example code snippets for integrating Textures.js with popular chart frameworks, so that developers can add textures more quickly to our applications!

* Chart.js
* TUI
* flot
* Highcharts
* D3
* Amcharts

**Comment by riccardoscalco** [comment]
Textures.js is designed to be used with d3, and the small code snippet in the readme should clarify the usage:

```
const svg = d3.select("#example")
  .append("svg");

const t = textures
  .lines()
  .thicker();

svg.call(t);

svg
  .append("circle")
  .style("fill", t.url());
```

Note that textures.js relies on d3 selections, therefore in any chart framework you can select an SVG node with d3 and then apply the texture following d3 patterns, for example:

```
const svg = d3.select("svg");

const t = textures
  .lines()
  .thicker();

svg.call(t);

svg
  .append("circle")
  .style("fill", t.url());
```
