### ISSUE TITLE
Link to repository on website

### ISSUE THREAD

**Issue by davenquinn** [riccardoscalco/textures#5]
Maybe this is more an issue with your personal site...but you have a beautiful and compelling intro page for this repository, only to have no link to the code! It took searching your name on Github to find the actual repo, so I could star it for later.

Please add a link to the specimen page. This is wonderful work!

**Comment by davelandry** [comment]
There's a link right on the bottom of the first panel!

![texture](https://cloud.githubusercontent.com/assets/1847581/6715502/54322d82-cd75-11e4-9e73-169f6bb1b512.png)

**Comment by davenquinn** [comment]
I swear it wasn't there earlier!

But all seems in order now...seems like it was just below the fold, and I missed it. Guess the coffee hadn't properly kicked in yet.

Fantastic-looking maps!
